on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        racket-variant: ["CS"]
        racket-version: ["stable"]
    name: Build on ${{ matrix.racket-variant }} Racket
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.10
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}
      - name: Install Package and its Dependencies
        run: raco pkg install --auto --batch
      - name: Check compilation
        run: raco exe --gui main.rkt
      - name: Check test
        run: raco test main.rkt
